#!/bin/bash

# Lizzy 2.0 - API Key Setup Script
# This script helps you configure your API keys

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Lizzy 2.0 - API Key Setup"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/n): " overwrite
    if [ "$overwrite" != "y" ]; then
        echo "Aborted. Edit .env manually if needed."
        exit 0
    fi
fi

# OpenAI API Key (Required)
echo ""
echo "─────────────────────────────────────────────────────────"
echo "OpenAI API Key (REQUIRED)"
echo "─────────────────────────────────────────────────────────"
echo "Get your key from: https://platform.openai.com/api-keys"
echo ""
read -p "Enter your OpenAI API key: " openai_key

if [ -z "$openai_key" ]; then
    echo "❌ OpenAI API key is required!"
    exit 1
fi

# Cohere API Key (Optional)
echo ""
echo "─────────────────────────────────────────────────────────"
echo "Cohere API Key (OPTIONAL - for reranking)"
echo "─────────────────────────────────────────────────────────"
echo "Get your key from: https://dashboard.cohere.com/api-keys"
echo "Press Enter to skip if you don't have one."
echo ""
read -p "Enter your Cohere API key (or press Enter to skip): " cohere_key

# Create .env file
cat > .env << EOF
# Lizzy 2.0 - API Configuration
# Generated by setup_keys.sh on $(date)

# OpenAI API Key (Required)
OPENAI_API_KEY=$openai_key

# Cohere API Key (Optional - for reranking)
COHERE_API_KEY=${cohere_key:-not-set}
EOF

echo ""
echo "✅ API keys saved to .env"
echo ""

# Test if keys work
echo "─────────────────────────────────────────────────────────"
echo "Testing API keys..."
echo "─────────────────────────────────────────────────────────"

# Source the .env file
export $(cat .env | grep -v '^#' | xargs)

# Test OpenAI key
echo -n "Testing OpenAI API key... "
if command -v python3 &> /dev/null; then
    python3 -c "
import os
from openai import OpenAI
try:
    client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))
    models = client.models.list()
    print('✅ Valid')
except Exception as e:
    print(f'❌ Invalid: {e}')
" 2>/dev/null
else
    echo "⚠️  Python3 not found, skipping validation"
fi

# Test Cohere key (if provided)
if [ "$cohere_key" != "" ] && [ "$cohere_key" != "not-set" ]; then
    echo -n "Testing Cohere API key... "
    if command -v python3 &> /dev/null; then
        python3 -c "
import os
try:
    import cohere
    co = cohere.Client(os.getenv('COHERE_API_KEY'))
    print('✅ Valid')
except ImportError:
    print('⚠️  Cohere package not installed (pip install cohere)')
except Exception as e:
    print(f'❌ Invalid: {e}')
" 2>/dev/null
    fi
fi

echo ""
echo "─────────────────────────────────────────────────────────"
echo "Setup complete!"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Your API keys are stored in: .env"
echo ""
echo "Next steps:"
echo "  1. Source the .env file: source .env"
echo "  2. Or run: export \$(cat .env | grep -v '^#' | xargs)"
echo "  3. Start using Lizzy: python3 -m lizzy.start"
echo ""
echo "Note: .env is in .gitignore and won't be pushed to GitHub"
echo ""
